services:
  server:
    image: httpd:2.4
    ports:
      - 8080:80
    volumes:
      - ../src/:/usr/local/apache2/htdocs/
    networks:
      - default

  tester:
    image: grafana/k6:1.4.0-with-browser
    volumes:
      - ../test/:/opt/k6/
    working_dir: /opt/k6/
    depends_on:
      - server
    networks:
      - default

  checker:
    image: denoland/deno:2.5.6
    volumes:
      - ../:/opt/timer/
    working_dir: /opt/timer/
